name: Java CI with Gradle - Build

on:
  push:
    branches: [ dev, main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3.9.0
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Build Target
        uses: actions/upload-artifact@v3.1.1
        with:
          name: "CatSero-Artifact"
          path: build/

      - name: Upload Build Jar
        uses: actions/upload-artifact@v3.1.1
        with:
          name: "CatSero-Jar"
          path: build/libs/CatSero*.jar
